/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg2_monicacastillo;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Monica
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() throws IOException {
        initComponents();
        ac.cargarArchivo();
        DefaultListModel modelo = new DefaultListModel();
        for (Computadora c : ac.getListacomputadoras()) {
            modelo.addElement(c);
            ListaComputadoras.setModel(modelo);
        } // Fin Fore
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
        for (Computadora c : ac.getListacomputadoras()) {
            modelo2.addElement(c);
        } // Fin For
        CBModificarComputadora.setModel(modelo2);
        DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
        for (Computadora c : ac.getListacomputadoras()) {
            modelo3.addElement(c);
        } // Fin For
        CBEliminarComputadora.setModel(modelo2);
        ac.escribirArchivo();
        at.CargarArchivo();
        DefaultListModel model = new DefaultListModel();
        for (Tecnico t : at.getListatecnico()) {
            model.addElement(t);
            ListaTecnicos.setModel(model);
        } // Fin Fore
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        for (Tecnico t : at.getListatecnico()) {
            model2.addElement(t);
        } // Fin For
        CBModificarTecnico.setModel(model2);
        DefaultComboBoxModel model3 = new DefaultComboBoxModel();
        for (Tecnico t : at.getListatecnico()) {
            model3.addElement(t);
        } // Fin For
        CBEliminarTecnico.setModel(model2);
        at.EscribirArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        VentanaModificarComputadora = new javax.swing.JDialog();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        NumSerieCompModi = new javax.swing.JFormattedTextField();
        jLabel39 = new javax.swing.JLabel();
        AñoCompModi = new javax.swing.JFormattedTextField();
        jLabel40 = new javax.swing.JLabel();
        ColorCompuModi = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        MaterialCompuModi = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        MarcaRamModi = new javax.swing.JTextField();
        TamañoRamModi = new javax.swing.JFormattedTextField();
        TiempoERamModi = new javax.swing.JFormattedTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        TamañoDiscoModi = new javax.swing.JFormattedTextField();
        jLabel48 = new javax.swing.JLabel();
        MarcaDiscoModi = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        TiempoEDiscoModi = new javax.swing.JFormattedTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        CapHorasBateriaModi = new javax.swing.JFormattedTextField();
        jLabel52 = new javax.swing.JLabel();
        MaterialBateriaModi = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        TiempoEBateriaModi = new javax.swing.JFormattedTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        MaterialTecladoModi = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        ColorTecladoModi = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        TiempoETecladoModi = new javax.swing.JFormattedTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        RBTactilPantallaModi = new javax.swing.JRadioButton();
        RBNoTactilPantallaModi = new javax.swing.JRadioButton();
        jLabel60 = new javax.swing.JLabel();
        TipoPantallaModi = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        TiempoEPantallaModi = new javax.swing.JFormattedTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        NumNucleosProcesadorModi = new javax.swing.JFormattedTextField();
        jLabel64 = new javax.swing.JLabel();
        VelocidadProcesadorModi = new javax.swing.JFormattedTextField();
        jLabel65 = new javax.swing.JLabel();
        TiempoEProcesadorModi = new javax.swing.JFormattedTextField();
        BotonModificarComputadora = new javax.swing.JButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        NumeroDeSerieComputadora = new javax.swing.JTextField();
        ColorComputadora = new javax.swing.JButton();
        AñoComputadora = new javax.swing.JTextField();
        MaterialComputadora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TamañoRAM = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MarcaRAM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MarcaDiscoDuro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TamañoDiscoDuro = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CapacidadHorasBateria = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        MaterialBateria = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        MaterialTeclado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ColorTeclado = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        RBTactilPantalla = new javax.swing.JRadioButton();
        RBNoTactilPantalla = new javax.swing.JRadioButton();
        TipoPantalla = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        NumNucleosProcesador = new javax.swing.JFormattedTextField();
        VelocidadProcesador = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        BotonAgregarComputadora = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        TiempoEnsamblajeRAM = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        TiempoEnsamblajeDiscoDuro = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        TiempoEnsamblajeBateria = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        TiempoEnsamblajeTeclado = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        TiempoEnsamblajePantalla = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        TiempoEnsamblajeProcesador = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        CBModificarComputadora = new javax.swing.JComboBox<>();
        BotonIrAModificarCompu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CBEliminarComputadora = new javax.swing.JComboBox<>();
        BotonEliminarComputadora = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        NombreTecnico = new javax.swing.JTextField();
        EdadTecnico = new javax.swing.JFormattedTextField();
        AgregarTecnico = new javax.swing.JButton();
        RBMujer = new javax.swing.JRadioButton();
        RBHombre = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        CBModificarTecnico = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        CBEliminarTecnico = new javax.swing.JComboBox<>();
        BotonEliminarTecnico = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaComputadoras = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaTecnicos = new javax.swing.JList<>();

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Modificar Computadora");

        jLabel38.setText("Numero de Serie:");

        NumSerieCompModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel39.setText("Año:");

        AñoCompModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel40.setText("Color:");

        jLabel41.setText("Material:");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("RAM:");

        jLabel43.setText("Tamaño:");

        jLabel44.setText("Marca:");

        jLabel45.setText("Tiempo Ensamblaje:");

        TamañoRamModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        TiempoERamModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Disco Duro:");

        jLabel47.setText("Tamaño:");

        TamañoDiscoModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel48.setText("Marca:");

        jLabel49.setText("Tiempo Ensamblaje:");

        TiempoEDiscoModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Bateria:");

        jLabel51.setText("Capacidad Horas:");

        CapHorasBateriaModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel52.setText("Material:");

        jLabel53.setText("Tiempo Ensamblaje:");

        TiempoEBateriaModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Teclado:");

        jLabel55.setText("Material:");

        jLabel56.setText("Color:");

        jLabel57.setText("Tiempo Ensamblaje:");

        TiempoETecladoModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Pantalla:");

        jLabel59.setText("Tactil:");

        buttonGroup3.add(RBTactilPantallaModi);
        RBTactilPantallaModi.setText("Tactil");

        buttonGroup3.add(RBNoTactilPantallaModi);
        RBNoTactilPantallaModi.setText("No Tactil");

        jLabel60.setText("Tipo:");

        jLabel61.setText("Tiempo Ensamblaje:");

        TiempoEPantallaModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Procesador");

        jLabel63.setText("Num Nucleos:");

        NumNucleosProcesadorModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel64.setText("Velocidad:");

        VelocidadProcesadorModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel65.setText("Tiempo Ensamblaje:");

        TiempoEProcesadorModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        BotonModificarComputadora.setText("Modificar Computadora");
        BotonModificarComputadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonModificarComputadoraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VentanaModificarComputadoraLayout = new javax.swing.GroupLayout(VentanaModificarComputadora.getContentPane());
        VentanaModificarComputadora.getContentPane().setLayout(VentanaModificarComputadoraLayout);
        VentanaModificarComputadoraLayout.setHorizontalGroup(
            VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MarcaRamModi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumSerieCompModi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AñoCompModi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColorCompuModi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialCompuModi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(52, 52, 52)
                        .addComponent(TamañoRamModi))
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoERamModi))
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MarcaDiscoModi, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(TamañoDiscoModi)))
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoEDiscoModi))
                    .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialBateriaModi)
                            .addComponent(CapHorasBateriaModi)))
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoEBateriaModi)))
                .addGap(47, 47, 47)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56))
                        .addGap(44, 44, 44)
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ColorTecladoModi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialTecladoModi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoETecladoModi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel59)
                            .addComponent(jLabel60))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TipoPantallaModi)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarComputadoraLayout.createSequentialGroup()
                                .addComponent(RBTactilPantallaModi)
                                .addGap(10, 10, 10)
                                .addComponent(RBNoTactilPantallaModi))))
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoEPantallaModi))
                    .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(jLabel64))
                        .addGap(18, 18, 18)
                        .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumNucleosProcesadorModi)
                            .addComponent(VelocidadProcesadorModi)))
                    .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoEProcesadorModi))
                    .addComponent(BotonModificarComputadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaModificarComputadoraLayout.setVerticalGroup(
            VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaModificarComputadoraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(NumSerieCompModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AñoCompModi)
                        .addComponent(jLabel55)
                        .addComponent(MaterialTecladoModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ColorCompuModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(ColorTecladoModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaterialCompuModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel57)
                        .addComponent(TiempoETecladoModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(TamañoRamModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(RBTactilPantallaModi)
                    .addComponent(RBNoTactilPantallaModi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(MarcaRamModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(TipoPantallaModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(TiempoERamModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61)
                    .addComponent(TiempoEPantallaModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(TamañoDiscoModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63)
                    .addComponent(NumNucleosProcesadorModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(MarcaDiscoModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(VelocidadProcesadorModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(TiempoEDiscoModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65)
                    .addComponent(TiempoEProcesadorModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(CapHorasBateriaModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaterialBateriaModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonModificarComputadora)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaModificarComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(TiempoEBateriaModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ColorComputadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorComputadoraMouseClicked(evt);
            }
        });

        jLabel2.setText("Numero de serie:");

        jLabel3.setText("Año:");

        jLabel4.setText("Color:");

        jLabel5.setText("Material:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("RAM:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Computadora");

        TamañoRAM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel7.setText("Tamaño:");

        jLabel8.setText("Marca:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Disco Duro:");

        jLabel10.setText("Tamaño:");

        jLabel11.setText("Marca:");

        TamañoDiscoDuro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Batería:");

        jLabel13.setText("Capacidad de horas:");

        CapacidadHorasBateria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel14.setText("Material:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Teclado:");

        jLabel16.setText("Material:");

        jLabel17.setText("Color:");

        ColorTeclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorTecladoMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Pantalla:");

        jLabel19.setText("Tactil:");

        jLabel20.setText("Tipo:");

        buttonGroup1.add(RBTactilPantalla);
        RBTactilPantalla.setText("Tactil");

        buttonGroup1.add(RBNoTactilPantalla);
        RBNoTactilPantalla.setText("No Tactil");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Procesador:");

        jLabel22.setText("Numero de nucleos:");

        NumNucleosProcesador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        VelocidadProcesador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel23.setText("Velocidad:");

        BotonAgregarComputadora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonAgregarComputadora.setText("Agregar Computadora");
        BotonAgregarComputadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarComputadoraMouseClicked(evt);
            }
        });

        jLabel24.setText("Tiempo Ensamblaje:");

        TiempoEnsamblajeRAM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel25.setText("Tiempo Ensamblaje:");

        jLabel26.setText("Tiempo Ensamblaje:");

        TiempoEnsamblajeBateria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel27.setText("Tiempo Ensamblaje:");

        TiempoEnsamblajeTeclado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel28.setText("Tiempo Ensamblaje:");

        TiempoEnsamblajePantalla.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel29.setText("Tiempo Ensamblaje:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TiempoEnsamblajeDiscoDuro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoEnsamblajeRAM))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AñoComputadora)
                            .addComponent(ColorComputadora, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroDeSerieComputadora))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialComputadora)
                            .addComponent(TamañoRAM)
                            .addComponent(MarcaRAM)
                            .addComponent(TamañoDiscoDuro)
                            .addComponent(MarcaDiscoDuro))))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TiempoEnsamblajePantalla))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(TiempoEnsamblajeTeclado))
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CapacidadHorasBateria)
                                    .addComponent(MaterialBateria)
                                    .addComponent(TiempoEnsamblajeBateria, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MaterialTeclado)
                                    .addComponent(ColorTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RBTactilPantalla)
                                .addGap(18, 18, 18)
                                .addComponent(RBNoTactilPantalla)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(63, 63, 63)
                                .addComponent(TipoPantalla))
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumNucleosProcesador)
                                    .addComponent(VelocidadProcesador)
                                    .addComponent(TiempoEnsamblajeProcesador, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(BotonAgregarComputadora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NumeroDeSerieComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AñoComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(CapacidadHorasBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ColorComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(MaterialBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoEnsamblajeBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaterialComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaterialTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TamañoRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ColorTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TiempoEnsamblajeTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MarcaRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(RBTactilPantalla)
                    .addComponent(RBNoTactilPantalla)
                    .addComponent(jLabel24)
                    .addComponent(TiempoEnsamblajeRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel20)
                    .addComponent(TipoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(TiempoEnsamblajePantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TamañoDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(MarcaDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22)
                    .addComponent(NumNucleosProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VelocidadProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel25))
                    .addComponent(TiempoEnsamblajeDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(TiempoEnsamblajeProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(BotonAgregarComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Computadora", jPanel1);

        BotonIrAModificarCompu.setText("Modificar Computadora");
        BotonIrAModificarCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIrAModificarCompuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(CBModificarComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(BotonIrAModificarCompu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CBModificarComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(BotonIrAModificarCompu)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Computadora", jPanel2);

        BotonEliminarComputadora.setText("Eliminar Computadora");
        BotonEliminarComputadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEliminarComputadoraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(CBEliminarComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(BotonEliminarComputadora)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(CBEliminarComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BotonEliminarComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Computadora", jPanel3);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Tecnico");

        jLabel33.setText("Nombre:");

        jLabel34.setText("Edad:");

        jLabel35.setText("Genero:");

        EdadTecnico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        AgregarTecnico.setText("Agregar Tecnico");
        AgregarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarTecnicoMouseClicked(evt);
            }
        });

        buttonGroup2.add(RBMujer);
        RBMujer.setText("Mujer");

        buttonGroup2.add(RBHombre);
        RBHombre.setText("Hombre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 201, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel34)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33)
                                        .addComponent(jLabel35))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addComponent(EdadTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addGap(86, 86, 86)
                                            .addComponent(RBMujer)
                                            .addGap(66, 66, 66)
                                            .addComponent(RBHombre))))))
                        .addGap(179, 179, 179))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(296, 296, 296)
                        .addComponent(AgregarTecnico)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel32)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(NombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(EdadTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(RBMujer)
                    .addComponent(RBHombre))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(AgregarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Tecnico", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(CBModificarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(CBModificarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Tecnico", jPanel5);

        BotonEliminarTecnico.setText("Eliminar Tecnico");
        BotonEliminarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEliminarTecnicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(CBEliminarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(BotonEliminarTecnico)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(CBEliminarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BotonEliminarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Tecnico", jPanel6);

        ListaComputadoras.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(ListaComputadoras);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Computadoras:");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Tecnicos:");

        ListaTecnicos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(ListaTecnicos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Visualizar", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarComputadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarComputadoraMouseClicked
        // TODO add your handling code here:
        try {
            String materialcomp, marcaram, marcadisco, materialbateria, materialteclado, tipopantalla;
            int numseriecomp, añocomp, tamañoram, tamañodisco, tiemporam, tiempodisco, tiempobateria, tiempoteclado, tiempopantalla, tiempoprocesador, caphorasbateria, numnucleosprocesador;
            Color colorcompu, colorteclado;
            boolean tactilpantalla;
            double velocidadprocesador;
            tamañoram = Integer.parseInt(TamañoRAM.getText());
            marcaram = MarcaRAM.getText();
            tiemporam = Integer.parseInt(TiempoEnsamblajeRAM.getText());
            RAM ram = new RAM(tamañoram, marcaram, tiemporam);
            tamañodisco = Integer.parseInt(TamañoDiscoDuro.getText());
            marcadisco = MarcaDiscoDuro.getText();
            tiempodisco = Integer.parseInt(TiempoEnsamblajeRAM.getText());
            DiscoDuro disco = new DiscoDuro(tamañodisco, marcadisco, tiempodisco);
            caphorasbateria = Integer.parseInt(CapacidadHorasBateria.getText());
            materialbateria = MaterialBateria.getText();
            tiempobateria = Integer.parseInt(TiempoEnsamblajeBateria.getText());
            Bateria bateria = new Bateria(caphorasbateria, materialbateria, tiempobateria);
            materialteclado = MaterialTeclado.getText();
            colorteclado = ColorTeclado.getBackground();
            tiempoteclado = Integer.parseInt(TiempoEnsamblajeTeclado.getText());
            Teclado teclado = new Teclado(materialteclado, colorteclado, tiempoteclado);
            if (RBTactilPantalla.isSelected()) {
                tactilpantalla = true;
            } else {
                tactilpantalla = false;
            } // Fin If
            tipopantalla = TipoPantalla.getText();
            tiempopantalla = Integer.parseInt(TiempoEnsamblajePantalla.getText());
            Pantalla pantalla = new Pantalla(tactilpantalla, tipopantalla, tiempopantalla);
            numnucleosprocesador = Integer.parseInt(NumNucleosProcesador.getText());
            velocidadprocesador = Double.parseDouble(VelocidadProcesador.getText());
            tiempoprocesador = Integer.parseInt(TiempoEnsamblajeProcesador.getText());
            Procesador procesador = new Procesador(numnucleosprocesador, velocidadprocesador, tiempoprocesador);
            numseriecomp = Integer.parseInt(NumeroDeSerieComputadora.getText());
            añocomp = Integer.parseInt(AñoComputadora.getText());
            colorcompu = ColorComputadora.getBackground();
            materialcomp = MaterialComputadora.getText();
            Computadora comp = new Computadora(numseriecomp, añocomp, colorcompu, materialcomp, ram, disco, bateria, teclado, pantalla, procesador);
            ac.cargarArchivo();
            ac.SetCompuadora(comp);
            DefaultListModel modelo = new DefaultListModel();
            for (Computadora c : ac.getListacomputadoras()) {
                modelo.addElement(c);
                ListaComputadoras.setModel(modelo);
            } // Fin Fore
            DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
            for (Computadora c : ac.getListacomputadoras()) {
                modelo2.addElement(c);
            } // Fin For
            CBModificarComputadora.setModel(modelo2);
            DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
            for (Computadora c : ac.getListacomputadoras()) {
                modelo3.addElement(c);
            } // Fin For
            CBEliminarComputadora.setModel(modelo3);
            ac.escribirArchivo();
            JOptionPane.showMessageDialog(this, "¡La computadora se ha agregado exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "¡Ha ocurrido un error!");
        } // Fin Try Catch
    }//GEN-LAST:event_BotonAgregarComputadoraMouseClicked

    private void ColorComputadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorComputadoraMouseClicked
        // TODO add your handling code here:
        try {
            Color color;
            color = JColorChooser.showDialog(this, "Elija un color: ", Color.yellow);
            ColorComputadora.setBackground(color);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "¡Ha ocurrido un error!");
        } // Fin Try Catch
    }//GEN-LAST:event_ColorComputadoraMouseClicked

    private void ColorTecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorTecladoMouseClicked
        // TODO add your handling code here:
        try {
            Color color;
            color = JColorChooser.showDialog(this, "Elija un color: ", Color.yellow);
            ColorTeclado.setBackground(color);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "¡Ha ocurrido un error!");
        } // Fin Try Catch
    }//GEN-LAST:event_ColorTecladoMouseClicked

    private void AgregarTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTecnicoMouseClicked
        // TODO add your handling code here:
        try {
            String nombre, genero;
            int edad;
            nombre = NombreTecnico.getText();
            edad = Integer.parseInt(EdadTecnico.getText());
            if (RBMujer.isSelected()) {
                genero = "Mujer";
            } else {
                genero = "Hombre";
            } // Fin If
            Tecnico tecnico = new Tecnico(nombre, edad, genero, 0);
            at.CargarArchivo();
            at.SetTecnico(tecnico);
            DefaultListModel modelo = new DefaultListModel();
            for (Tecnico t : at.getListatecnico()) {
                modelo.addElement(t);
                ListaTecnicos.setModel(modelo);
            } // Fin Fore
            DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
            for (Tecnico t : at.getListatecnico()) {
                modelo2.addElement(t);
            } // Fin For
            CBModificarTecnico.setModel(modelo2);
            DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
            for (Tecnico t : at.getListatecnico()) {
                modelo3.addElement(t);
            } // Fin For
            CBEliminarTecnico.setModel(modelo2);
            at.EscribirArchivo();
            JOptionPane.showMessageDialog(this, "¡Se ha agregado exitosamente un tecnico!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "¡Ha ocurrido un error!");
        } // Fin Try Catch
    }//GEN-LAST:event_AgregarTecnicoMouseClicked

    private void BotonEliminarComputadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarComputadoraMouseClicked
        // TODO add your handling code here:
        try {
            Computadora co;
            int pos;
            pos = CBEliminarComputadora.getSelectedIndex();
            co = (Computadora) CBEliminarComputadora.getSelectedItem();
            ac.cargarArchivo();
            ac.getListacomputadoras().remove(pos);
            DefaultListModel modelo = new DefaultListModel();
            for (Computadora c : ac.getListacomputadoras()) {
                modelo.addElement(c);
            } // Fin Fore
            ListaComputadoras.setModel(modelo);
            DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
            for (Computadora c : ac.getListacomputadoras()) {
                modelo2.addElement(c);
            } // Fin For
            CBModificarComputadora.setModel(modelo2);
            DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
            for (Computadora c : ac.getListacomputadoras()) {
                modelo3.addElement(c);
            } // Fin For
            CBEliminarComputadora.setModel(modelo2);
            ac.escribirArchivo();
            JOptionPane.showMessageDialog(this, "¡Se ha eliminado exitosamente la computadora!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "¡Ha ocurrido un error!");
        } // Fin Try Catch
    }//GEN-LAST:event_BotonEliminarComputadoraMouseClicked

    private void BotonEliminarTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarTecnicoMouseClicked
        // TODO add your handling code here:
        try {
            int pos;
            pos = CBEliminarTecnico.getSelectedIndex();
            at.CargarArchivo();
            at.getListatecnico().remove(pos);
            DefaultListModel modelo = new DefaultListModel();
            for (Tecnico t : at.getListatecnico()) {
                modelo.addElement(t);
            } // Fin Fore
            ListaTecnicos.setModel(modelo);
            DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
            for (Tecnico t : at.getListatecnico()) {
                modelo2.addElement(t);
            } // Fin For
            CBModificarTecnico.setModel(modelo2);
            DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
            for (Tecnico t : at.getListatecnico()) {
                modelo3.addElement(t);
            } // Fin For
            CBEliminarTecnico.setModel(modelo2);
            at.EscribirArchivo();
            JOptionPane.showMessageDialog(this, "¡Se ha eliminado exitosamente el tecnico!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "¡Ha ocurrido un error!");
        } // Fin Try Catch
    }//GEN-LAST:event_BotonEliminarTecnicoMouseClicked

    private void BotonModificarComputadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModificarComputadoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonModificarComputadoraMouseClicked

    private void BotonIrAModificarCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIrAModificarCompuMouseClicked
        // TODO add your handling code here:
        try {
            Computadora c;
            RAM r;
            DiscoDuro dd;
            c = (Computadora) CBModificarComputadora.getSelectedItem();
            String ns = "", año = "", tamr = "", ter = "", tamdd = "", tedd = "";
            ns += c.getNumserie();
            año += c.getAño();
            NumeroDeSerieComputadora.setText(ns);
            AñoCompModi.setText(año);
            ColorCompuModi.setBackground(c.getColor());
            MaterialCompuModi.setText(c.getMaterial());
            r = c.getRam();
            tamr += r.getTamaño();
            ter += r.getTiempoensamblaje();
            TamañoRamModi.setText(tamr);
            MarcaRamModi.setText(r.getMarca());
            TiempoERamModi.setText(ter);
            dd = c.getDiscoduro();
            tamdd += dd.getTamaño();
            tedd += dd.getTiempoensamblaje();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "¡Ha ocurrido un error!");
        } // Fin Try Catch
    }//GEN-LAST:event_BotonIrAModificarCompuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarTecnico;
    private javax.swing.JFormattedTextField AñoCompModi;
    private javax.swing.JTextField AñoComputadora;
    private javax.swing.JButton BotonAgregarComputadora;
    private javax.swing.JButton BotonEliminarComputadora;
    private javax.swing.JButton BotonEliminarTecnico;
    private javax.swing.JButton BotonIrAModificarCompu;
    private javax.swing.JButton BotonModificarComputadora;
    private javax.swing.JComboBox<String> CBEliminarComputadora;
    private javax.swing.JComboBox<String> CBEliminarTecnico;
    private javax.swing.JComboBox<String> CBModificarComputadora;
    private javax.swing.JComboBox<String> CBModificarTecnico;
    private javax.swing.JFormattedTextField CapHorasBateriaModi;
    private javax.swing.JFormattedTextField CapacidadHorasBateria;
    private javax.swing.JButton ColorCompuModi;
    private javax.swing.JButton ColorComputadora;
    private javax.swing.JButton ColorTeclado;
    private javax.swing.JButton ColorTecladoModi;
    private javax.swing.JFormattedTextField EdadTecnico;
    private javax.swing.JList<String> ListaComputadoras;
    private javax.swing.JList<String> ListaTecnicos;
    private javax.swing.JTextField MarcaDiscoDuro;
    private javax.swing.JTextField MarcaDiscoModi;
    private javax.swing.JTextField MarcaRAM;
    private javax.swing.JTextField MarcaRamModi;
    private javax.swing.JTextField MaterialBateria;
    private javax.swing.JTextField MaterialBateriaModi;
    private javax.swing.JTextField MaterialCompuModi;
    private javax.swing.JTextField MaterialComputadora;
    private javax.swing.JTextField MaterialTeclado;
    private javax.swing.JTextField MaterialTecladoModi;
    private javax.swing.JTextField NombreTecnico;
    private javax.swing.JFormattedTextField NumNucleosProcesador;
    private javax.swing.JFormattedTextField NumNucleosProcesadorModi;
    private javax.swing.JFormattedTextField NumSerieCompModi;
    private javax.swing.JTextField NumeroDeSerieComputadora;
    private javax.swing.JRadioButton RBHombre;
    private javax.swing.JRadioButton RBMujer;
    private javax.swing.JRadioButton RBNoTactilPantalla;
    private javax.swing.JRadioButton RBNoTactilPantallaModi;
    private javax.swing.JRadioButton RBTactilPantalla;
    private javax.swing.JRadioButton RBTactilPantallaModi;
    private javax.swing.JFormattedTextField TamañoDiscoDuro;
    private javax.swing.JFormattedTextField TamañoDiscoModi;
    private javax.swing.JFormattedTextField TamañoRAM;
    private javax.swing.JFormattedTextField TamañoRamModi;
    private javax.swing.JFormattedTextField TiempoEBateriaModi;
    private javax.swing.JFormattedTextField TiempoEDiscoModi;
    private javax.swing.JFormattedTextField TiempoEPantallaModi;
    private javax.swing.JFormattedTextField TiempoEProcesadorModi;
    private javax.swing.JFormattedTextField TiempoERamModi;
    private javax.swing.JFormattedTextField TiempoETecladoModi;
    private javax.swing.JFormattedTextField TiempoEnsamblajeBateria;
    private javax.swing.JFormattedTextField TiempoEnsamblajeDiscoDuro;
    private javax.swing.JFormattedTextField TiempoEnsamblajePantalla;
    private javax.swing.JFormattedTextField TiempoEnsamblajeProcesador;
    private javax.swing.JFormattedTextField TiempoEnsamblajeRAM;
    private javax.swing.JFormattedTextField TiempoEnsamblajeTeclado;
    private javax.swing.JTextField TipoPantalla;
    private javax.swing.JTextField TipoPantallaModi;
    private javax.swing.JFormattedTextField VelocidadProcesador;
    private javax.swing.JFormattedTextField VelocidadProcesadorModi;
    private javax.swing.JDialog VentanaModificarComputadora;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
AdminComputadora ac = new AdminComputadora("./Computadoras.mc");
    AdminTecnico at = new AdminTecnico("./Tecnicos.txt");
}
